# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5474c9bb2d5634f305f5ed917236f45369ec3d0ef76754030b9cfa1cf484a9c1ee7362e792b5b6e6ef3607779f6e924fde78f67ae0efb0af6899963e262fca89

test:
  secret_key_base: 147a3c9cafb5d4739a0c4ad3b0ce5eaef4f7959360a15384fa810a894887fa2f2ef14b5df91d734e8ba27c350f58041fff1102378dcfddf9b405e68e79d18eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_password: <%= ENV["gmail_password"] %>